production:
  secret_key_base: 1fe081dac848dbb3e1e06a5bf1aeb7d3bddd4f990aeb8f0a369fff2e6916c1466416360eb00eef4cb21f5d5bfeacbad454dd10b9003c4b291ff981b04db4b9ed
  mindbody:
    :source_name: SpokehausStudios
    :api_key: zr/SsrmjXiE/l4HgrQj89eg9prQ=
    :username: Riley@spokehaus.ca
    :password: 70DanLeckie1!
    :site_id: 287986
    :log: false
    :log_level: :debug
    :shoe_size_field_id: 1
